//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use super::sea_orm_active_enums::RequirementCategory;
use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "batch_requirements")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub requirement_id: i32,
    pub batch_id: i32,
    pub category: RequirementCategory,
    #[sea_orm(column_type = "Decimal(Some((12, 2)))")]
    pub quantity: Decimal,
    pub unit: String,
    pub request_date: Date,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::batch_allocations::Entity")]
    BatchAllocations,
    #[sea_orm(
        belongs_to = "super::batches::Entity",
        from = "Column::BatchId",
        to = "super::batches::Column::BatchId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Batches,
}

impl Related<super::batch_allocations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BatchAllocations.def()
    }
}

impl Related<super::batches::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Batches.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
