//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub mod prelude;

pub mod batch_allocations;
pub mod batch_requirements;
pub mod batches;
pub mod bird_count_history;
pub mod bird_sell_history;
pub mod farmers;
pub mod items;
pub mod post;
pub mod production_lines;
pub mod purchases;
pub mod sea_orm_active_enums;
pub mod suppliers;
pub mod traders;
pub mod users;
